export const actions = {
  SET_LOADING: 'SET_LOADING',
  SET_CATEGORIES: 'SET_CATEGORIES',
  SET_THEMES: 'SET_THEMES',
  SET_INSTRUMENTS:'SET_INSTRUMENTS',
  SET_USERS: 'SET_USERS',
  UPDATE_INSTRUMENTS: 'UPDATE_INSTRUMENTS',
  FIND_INSTRUMENT: 'FIND_INSTRUMENT',
  UPDATE_FAVORITES: 'UPDATE_FAVORITES',
  TOGGLE_FAVORITE: 'TOGGLE_FAVORITE'
}
