export const actions = {
  SET_LOADING: 'SET_LOADING',
  SET_CATEGORIES: 'SET_CATEGORIES',
  UPDATE_INSTRUMENTS: 'UPDATE_INSTRUMENTS',
  FIND_INSTRUMENT: 'FIND_INSTRUMENT',
  UPDATE_FAVORITES: 'UPDATE_FAVORITES',
  TOGGLE_FAVORITE: 'TOGGLE_FAVORITE'
}
