version: '3.8'

services:
  java_music_house:
    container_name: container_music_house_v1_1.0.0
    image: music_house:1.0.0
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}

      TELEGRAM_BOT_USERNAME: ${TELEGRAM_BOT_USERNAME}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}

      BUCKET_NAME: ${BUCKET_NAME}
      ACCESS_KEY: ${ACCESS_KEY}
      SECRET_KEY: ${SECRET_KEY}
      REGION: ${REGION}
    depends_on:
      - mysql_container_music_house_v1_1.0.0
    networks:
      - my_net_music_house
    volumes:
      - ~/.m2:/root/.m2
    restart: always

  mysql_container_music_house_v1_1.0.0:
    container_name: mysql_container_music_house_v1_1.0.0
    image: mysql:latest
    ports:
      - "13307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_net_music_house
    restart: always

networks:
  my_net_music_house:
    driver: bridge

volumes:
  mysql_data: